import { Urbanist } from "next/font/google";
import "./globals.css";
import LenisSmooth from "./(components)/LenisSmooth";
import Header from "./(components)/Header";

import Script from "next/script";
import LayoutFooter from "./(components)/LayoutFooter";
import { Toaster } from "sonner";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Web Pioneers",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${urbanist.variable} font-urbanist antialiased`}
      >
        <Script
          src="https://cdn.lordicon.com/lordicon.js"
          strategy="beforeInteractive"
        />
        <LenisSmooth />
        <Header />
        {children}
        <LayoutFooter />
        <Toaster />
      </body>
    </html>
  );
}
